/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    FeatureSection: typeof import('./src/components/FeatureSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ResponsiveXPos: typeof import('./src/components/ResponsiveXPos.vue')['default']
    TestComp: typeof import('./src/components/TestComp.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TitleSection: typeof import('./src/components/TitleSection.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
