/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FeatureCard: typeof import('./src/components/FeatureSection/FeatureCard.vue')['default']
    FeatureSection: typeof import('./src/components/FeatureSection/FeatureSection.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainSection: typeof import('./src/components/MainSections/MainSection.vue')['default']
    PeopleSection: typeof import('./src/components/MainSections/PeopleSection/PeopleSection.vue')['default']
    PersonIntro: typeof import('./src/components/MainSections/PeopleSection/PersonIntro.vue')['default']
    ResponsiveXPos: typeof import('./src/components/ResponsiveXPos.vue')['default']
    SubSection: typeof import('./src/components/MainSections/SubSection.vue')['default']
    TestComp: typeof import('./src/components/TestComp.vue')['default']
    TitleSection: typeof import('./src/components/TitleSection/TitleSection.vue')['default']
    TitleSectionButton: typeof import('./src/components/TitleSection/TitleSectionButton.vue')['default']
    UseCaseCard: typeof import('./src/components/MainSections/UseCaseSection/UseCaseCard.vue')['default']
    UseCaseSection: typeof import('./src/components/MainSections/UseCaseSection/UseCaseSection.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
