<template>
    <div class="main-section">
        <div class="column">

            <SubSection title="Use Cases">
                <UseCaseSection />
            </SubSection>
            <SubSection title="Motivation">
                <!-- max 1000 px width -->
                <div class="max-w-[700px] mx-auto my-20 text-gray-300 text-justify">
                    <p class="mb-4">
                        In our daily lives, countless ideas emerge in our minds, only to be dismissed because the
                        perceived cost of realizing them is too high. Over time, sadly, we tend to forget our inherent
                        creativity.
                    </p>
                    <p class="mb-4">
                        The mission of Grapycal is to push more ideas over the line to be worthy of trying out.
                    </p>
                    <p class="mb-4">
                        Grapycal is helpful for conducting experiments, including training AI, physical simulations,
                        data analysis, computer art, and more. These experiments require repeated parameter adjustments,
                        swapping certain components of models, while simultaneously observing the phenomena generated by
                        different parameters. We then use human judgment combined with domain knowledge to deduce the
                        best model or other conclusions.
                    </p>
                    <p class="mb-4">
                        In this back-and-forth process between humans and machines, using traditional Python execution
                        methods or Jupyter notebooks can be cumbersome. Therefore, we need the higher interactivity
                        provided by Grapycal.
                    </p>
                </div>
            </SubSection>

            <SubSection title="Get Started">
                <a href="https://docs.grapycal.com/latest/docs/"
                    class="text-white py-2 px-4 rounded-md flex items-center text-gray-400 justify-center text-lg">
                    Documentation
                </a>
                <a href="https://docs.grapycal.com/latest/docs/get-started-6de726/installation-b8566b/"
                    class="text-white py-2 px-4 rounded-md flex items-center text-gray-400 justify-center text-lg">
                    Download Now
                </a>

            </SubSection>


            <PeopleSection></PeopleSection>
        </div>

    </div>
</template>

<script setup lang="ts">
// props: title

const props = defineProps({

})

</script>

<style scoped>
.main-section {
    background-color: var(--color-background);
}

.column {

    max-width: 1400px;
    padding: 50px 20px;
    margin: auto;
}
</style>